#!/bin/sh
#
# Loads the protein_gi_to_taxids table from a gzipped NCBI dump file.
#
# daniel.lundin@scilifelab.se

TABLE=protein_gi_to_taxids

usage() {
  echo "`basename $0`: Loads the protein_gi_to_taxids table in a PostgreSQL database with data from a gzipped NCBI dump file."
  echo "	`basename $0` -d database -U dbuser path/gi_taxid_prot.dmp.gz"
  echo
  echo "		-d database: Name of database to connect to"
  echo "		-U dbuser: Name of database user"
}

db=""
dbuser=""

while getopts :d:U:h opt; do
  case $opt in
    d )
      db=$OPTARG ;;
    h )
      usage; exit 0 ;;
    U )
      dbuser=$OPTARG ;;
    ? )
      echo "Unknonw option $opt"
      usage; exit 1 ;;
  esac
done
shift $(($OPTIND - 1))
dumpfile=$1

echo "Truncating $TABLE"
psql -d $db -U $dbuser -c "TRUNCATE TABLE $TABLE"

echo "Inserting rows from $dumpfile"
gunzip -c $dumpfile | psql -d $db -U $dbuser -c "COPY $TABLE(gi,taxid) FROM STDIN;"
