require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FetchGisController do

  # This should return the minimal set of attributes required to create a valid
  # FetchGi. As you add validations to FetchGi, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :gi => 14 }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FetchGisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fetch_gis as @fetch_gis" do
      fetch_gi = FetchGi.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fetch_gis).should eq([fetch_gi])
    end
  end

  describe "GET show" do
    it "assigns the requested fetch_gi as @fetch_gi" do
      fetch_gi = FetchGi.create! valid_attributes
      get :show, {:id => fetch_gi.to_param}, valid_session
      assigns(:fetch_gi).should eq(fetch_gi)
    end
  end

  describe "GET new" do
    it "assigns a new fetch_gi as @fetch_gi" do
      get :new, {}, valid_session
      assigns(:fetch_gi).should be_a_new(FetchGi)
    end
  end

  describe "GET edit" do
    it "assigns the requested fetch_gi as @fetch_gi" do
      fetch_gi = FetchGi.create! valid_attributes
      get :edit, {:id => fetch_gi.to_param}, valid_session
      assigns(:fetch_gi).should eq(fetch_gi)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FetchGi" do
        expect {
          post :create, {:fetch_gi => valid_attributes}, valid_session
        }.to change(FetchGi, :count).by(1)
      end

      it "assigns a newly created fetch_gi as @fetch_gi" do
        post :create, {:fetch_gi => valid_attributes}, valid_session
        assigns(:fetch_gi).should be_a(FetchGi)
        assigns(:fetch_gi).should be_persisted
      end

      it "redirects to the created fetch_gi" do
        post :create, {:fetch_gi => valid_attributes}, valid_session
        response.should redirect_to(FetchGi.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fetch_gi as @fetch_gi" do
        # Trigger the behavior that occurs when invalid params are submitted
        FetchGi.any_instance.stub(:save).and_return(false)
        post :create, {:fetch_gi => {}}, valid_session
        assigns(:fetch_gi).should be_a_new(FetchGi)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FetchGi.any_instance.stub(:save).and_return(false)
        post :create, {:fetch_gi => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fetch_gi" do
        fetch_gi = FetchGi.create! valid_attributes
        # Assuming there are no other fetch_gis in the database, this
        # specifies that the FetchGi created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FetchGi.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fetch_gi.to_param, :fetch_gi => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fetch_gi as @fetch_gi" do
        fetch_gi = FetchGi.create! valid_attributes
        put :update, {:id => fetch_gi.to_param, :fetch_gi => valid_attributes}, valid_session
        assigns(:fetch_gi).should eq(fetch_gi)
      end

      it "redirects to the fetch_gi" do
        fetch_gi = FetchGi.create! valid_attributes
        put :update, {:id => fetch_gi.to_param, :fetch_gi => valid_attributes}, valid_session
        response.should redirect_to(fetch_gi)
      end
    end

    describe "with invalid params" do
      it "assigns the fetch_gi as @fetch_gi" do
        fetch_gi = FetchGi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FetchGi.any_instance.stub(:save).and_return(false)
        put :update, {:id => fetch_gi.to_param, :fetch_gi => {}}, valid_session
        assigns(:fetch_gi).should eq(fetch_gi)
      end

      it "re-renders the 'edit' template" do
        fetch_gi = FetchGi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FetchGi.any_instance.stub(:save).and_return(false)
        put :update, {:id => fetch_gi.to_param, :fetch_gi => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fetch_gi" do
      fetch_gi = FetchGi.create! valid_attributes
      expect {
        delete :destroy, {:id => fetch_gi.to_param}, valid_session
      }.to change(FetchGi, :count).by(-1)
    end

    it "redirects to the fetch_gis list" do
      fetch_gi = FetchGi.create! valid_attributes
      delete :destroy, {:id => fetch_gi.to_param}, valid_session
      response.should redirect_to(fetch_gis_url)
    end
  end

end
