require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrganismGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # OrganismGroup. As you add validations to OrganismGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { 
      name: 'wgs',
      test: false
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrganismGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all organism_groups as @organism_groups" do
      organism_group = OrganismGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:organism_groups).should eq([organism_group])
    end
  end

  describe "GET show" do
    it "assigns the requested organism_group as @organism_group" do
      organism_group = OrganismGroup.create! valid_attributes
      get :show, {:id => organism_group.to_param}, valid_session
      assigns(:organism_group).should eq(organism_group)
    end
  end

  describe "GET new" do
    it "assigns a new organism_group as @organism_group" do
      get :new, {}, valid_session
      assigns(:organism_group).should be_a_new(OrganismGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested organism_group as @organism_group" do
      organism_group = OrganismGroup.create! valid_attributes
      get :edit, {:id => organism_group.to_param}, valid_session
      assigns(:organism_group).should eq(organism_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrganismGroup" do
        expect {
          post :create, {:organism_group => valid_attributes}, valid_session
        }.to change(OrganismGroup, :count).by(1)
      end

      it "assigns a newly created organism_group as @organism_group" do
        post :create, {:organism_group => valid_attributes}, valid_session
        assigns(:organism_group).should be_a(OrganismGroup)
        assigns(:organism_group).should be_persisted
      end

      it "redirects to the created organism_group" do
        post :create, {:organism_group => valid_attributes}, valid_session
        response.should redirect_to(OrganismGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organism_group as @organism_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismGroup.any_instance.stub(:save).and_return(false)
        post :create, {:organism_group => {}}, valid_session
        assigns(:organism_group).should be_a_new(OrganismGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismGroup.any_instance.stub(:save).and_return(false)
        post :create, {:organism_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organism_group" do
        organism_group = OrganismGroup.create! valid_attributes
        # Assuming there are no other organism_groups in the database, this
        # specifies that the OrganismGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrganismGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => organism_group.to_param, :organism_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested organism_group as @organism_group" do
        organism_group = OrganismGroup.create! valid_attributes
        put :update, {:id => organism_group.to_param, :organism_group => valid_attributes}, valid_session
        assigns(:organism_group).should eq(organism_group)
      end

      it "redirects to the organism_group" do
        organism_group = OrganismGroup.create! valid_attributes
        put :update, {:id => organism_group.to_param, :organism_group => valid_attributes}, valid_session
        response.should redirect_to(organism_group)
      end
    end

    describe "with invalid params" do
      it "assigns the organism_group as @organism_group" do
        organism_group = OrganismGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => organism_group.to_param, :organism_group => {}}, valid_session
        assigns(:organism_group).should eq(organism_group)
      end

      it "re-renders the 'edit' template" do
        organism_group = OrganismGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrganismGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => organism_group.to_param, :organism_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organism_group" do
      organism_group = OrganismGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => organism_group.to_param}, valid_session
      }.to change(OrganismGroup, :count).by(-1)
    end

    it "redirects to the organism_groups list" do
      organism_group = OrganismGroup.create! valid_attributes
      delete :destroy, {:id => organism_group.to_param}, valid_session
      response.should redirect_to(organism_groups_url)
    end
  end

end
