require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaxonAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # TaxonAttribute. As you add validations to TaxonAttribute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxonAttributesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all taxon_attributes as @taxon_attributes" do
      taxon_attribute = TaxonAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:taxon_attributes).should eq([taxon_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested taxon_attribute as @taxon_attribute" do
      taxon_attribute = TaxonAttribute.create! valid_attributes
      get :show, {:id => taxon_attribute.to_param}, valid_session
      assigns(:taxon_attribute).should eq(taxon_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new taxon_attribute as @taxon_attribute" do
      get :new, {}, valid_session
      assigns(:taxon_attribute).should be_a_new(TaxonAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested taxon_attribute as @taxon_attribute" do
      taxon_attribute = TaxonAttribute.create! valid_attributes
      get :edit, {:id => taxon_attribute.to_param}, valid_session
      assigns(:taxon_attribute).should eq(taxon_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaxonAttribute" do
        expect {
          post :create, {:taxon_attribute => valid_attributes}, valid_session
        }.to change(TaxonAttribute, :count).by(1)
      end

      it "assigns a newly created taxon_attribute as @taxon_attribute" do
        post :create, {:taxon_attribute => valid_attributes}, valid_session
        assigns(:taxon_attribute).should be_a(TaxonAttribute)
        assigns(:taxon_attribute).should be_persisted
      end

      it "redirects to the created taxon_attribute" do
        post :create, {:taxon_attribute => valid_attributes}, valid_session
        response.should redirect_to(TaxonAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taxon_attribute as @taxon_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:taxon_attribute => {}}, valid_session
        assigns(:taxon_attribute).should be_a_new(TaxonAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:taxon_attribute => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taxon_attribute" do
        taxon_attribute = TaxonAttribute.create! valid_attributes
        # Assuming there are no other taxon_attributes in the database, this
        # specifies that the TaxonAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TaxonAttribute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => taxon_attribute.to_param, :taxon_attribute => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested taxon_attribute as @taxon_attribute" do
        taxon_attribute = TaxonAttribute.create! valid_attributes
        put :update, {:id => taxon_attribute.to_param, :taxon_attribute => valid_attributes}, valid_session
        assigns(:taxon_attribute).should eq(taxon_attribute)
      end

      it "redirects to the taxon_attribute" do
        taxon_attribute = TaxonAttribute.create! valid_attributes
        put :update, {:id => taxon_attribute.to_param, :taxon_attribute => valid_attributes}, valid_session
        response.should redirect_to(taxon_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the taxon_attribute as @taxon_attribute" do
        taxon_attribute = TaxonAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => taxon_attribute.to_param, :taxon_attribute => {}}, valid_session
        assigns(:taxon_attribute).should eq(taxon_attribute)
      end

      it "re-renders the 'edit' template" do
        taxon_attribute = TaxonAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => taxon_attribute.to_param, :taxon_attribute => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taxon_attribute" do
      taxon_attribute = TaxonAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => taxon_attribute.to_param}, valid_session
      }.to change(TaxonAttribute, :count).by(-1)
    end

    it "redirects to the taxon_attributes list" do
      taxon_attribute = TaxonAttribute.create! valid_attributes
      delete :destroy, {:id => taxon_attribute.to_param}, valid_session
      response.should redirect_to(taxon_attributes_url)
    end
  end

end
